# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Eduardo Lauer
email: edulauer@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  Experienced Unity developer with games designed, developed, and published.
  Self-driven developer with good analytical and problem solving skills.
  Design and develop solutions following good practices that deliver functional and reliable products.
  Constantly learning new technologies and methods to increase quality and efficiency.
url: https://eduardolauer.com
repository: "edumlauer/website"
twitter_username: edumlauer
github_username: edumlauer
minimal_mistakes_skin: dark
search: false

twitter:
  username: "edumlauer"

social:
type:  # Person or Organization (defaults to Person)
name:  # If the user or organization name differs from the site's name
links:
  - "https://twitter.com/edumlauer"
  - "https://github.com/edumlauer"
  - "https://www.linkedin.com/in/edulauer"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-2Y4MFN1GMF"
    anonymize_ip: false # default

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
timezone: America/Sao_Paulo # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
#  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache

author:
  name: "Eduardo Lauer"
  avatar: "/assets/images/photo.png"
  bio: "👾 Unity Game Developer"
  location: "Brazil"
  links:
    - label: "edulauer@pm.me"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:edulauer@pm.me"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/edumlauer"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/edumlauer"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/edulauer/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/edumlauer"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/edumlauer"
    - label: "Linkedin"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/edulauer/"

defaults:
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
# _projects
  - scope:
      path: "_projects"
      type: projects
    values:
      layout: single
      author_profile: false
      share: true

collections:
  projects:
    output: true
    permalink: /:collection/:path/

atom_feed:
  hide: true